VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "thoughtbot/ubuntu-14-04-server"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../role.yml"
    ansible.sudo = true
    ansible.host_key_checking = false
  end

end
